import { test, expect } from './helpers/map-test';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
const captureDir = '../artifacts';
async function capture(page, name) {
  if (name === 'desktop-plan' || name.endsWith('-route')) await expect(page.locator('.map-wrap:visible')).toBeVisible();
  await page.evaluate(() => document.fonts.ready);
  if (await page.locator('.map-wrap:visible').count()) {
    await expect(page.locator('.leaflet-container:visible')).toBeVisible();
    await expect(page.locator('.route-waypoint').first()).toBeVisible();
    await expect(page.locator('.map-wrap:visible')).toHaveAttribute('data-tiles-ready', 'true', { timeout: 25000 });
    await expect.poll(() => page.locator('.leaflet-tile-loaded').evaluateAll(tiles => tiles.length > 0 && tiles.every(tile => Number(getComputedStyle(tile).opacity) >= 0.99)), { timeout: 25000 }).toBeTruthy();
  }
  await page.waitForTimeout(200);
  await mkdir(captureDir, { recursive: true }); await page.screenshot({ path: `${captureDir}/${name}.png`, fullPage: true });
}
async function assertFits(page) { expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy(); }

test('live trip: route, instructions, responsive views, daily graph and download', async ({ page, mapTileRequests }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  const origin = new URL(process.env.PLAYWRIGHT_BASE_URL || 'http://127.0.0.1:5180').origin;
  await page.route(url => url.origin === origin && ['/', '/plan', '/route', '/logs'].includes(url.pathname), async route => {
    const response = await route.fetch();
    await route.fulfill({response,headers:{...response.headers(),'referrer-policy':'same-origin'}});
  });
  await page.goto('/'); await page.evaluate(() => document.fonts.ready);
  await expect(page.getByRole('heading', { name: 'Plan your next haul' })).toBeVisible();
  await page.getByRole('tab', { name: 'Route & stops', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Plan a trip to see your route and stops' })).toBeVisible();
  await page.getByRole('tab', { name: 'Daily logs', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Plan a trip to generate your log sheets' })).toBeVisible();
  await capture(page, 'desktop-empty-logs');
  await page.getByRole('button', { name: 'Enter trip details →' }).click();
  await capture(page, 'desktop-plan');
  expect(mapTileRequests.length).toBeGreaterThan(0);
  expect(mapTileRequests.every(request => request.referer === `${origin}/`)).toBeTruthy();
  const responsePromise = page.waitForResponse(r => r.url().includes('/api/trips/plan/') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Plan route & logs →' }).click();
  const response = await responsePromise; expect(response.status()).toBe(200);
  const plan = await response.json();
  expect(plan.summary.inspections).toBe(2);
  await mkdir(captureDir, { recursive: true }); await writeFile(`${captureDir}/live-plan.json`, JSON.stringify(plan, null, 2));
  await expect(page.getByRole('heading', { name: /Chicago to/ })).toBeVisible();
  await expect(page.getByText('Trip itinerary', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: /Show Pre-trip \/ TIV/ })).toBeVisible();
  await expect(page.getByRole('button', { name: /Show Post-trip \/ TIV/ })).toBeVisible();
  await page.getByRole('tab', { name: 'Daily logs', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Planned daily logs' })).toBeVisible();
  await expect(page.locator('.log-desktop .remarks')).toContainText('Pre-trip inspection / TIV');
  await expect(page.locator('.log-desktop .remarks')).toContainText('Post-trip inspection / TIV');
  const pretrip = page.locator('.log-desktop [data-log-activity^="Pre-trip inspection"]');
  await pretrip.locator('.activity-hit').hover();
  await expect(page.getByRole('tooltip')).toContainText('15m');
  await expect(page.getByRole('tooltip')).toContainText('counts as work');
  await capture(page, 'desktop-log-hover');
  await pretrip.press('Escape');
  await expect(page.getByRole('tooltip')).toBeHidden();
  const posttrip = page.locator('.log-desktop [data-log-activity^="Post-trip inspection"]');
  await posttrip.focus();
  await expect(page.getByRole('tooltip')).toContainText('Post-trip inspection');
  await expect(page.getByRole('tooltip')).toContainText('15m');
  await posttrip.press('Escape');
  await page.getByRole('tab', { name: 'Route & stops', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Chicago to/ })).toBeVisible();
  expect(plan.daily_logs.every(log => Math.abs(log.total_hours - 24) < 1e-9)).toBeTruthy();
  await assertFits(page); await capture(page, 'desktop-route');
  await page.getByRole('button', { name: /Chicago → Springfield/ }).click();
  await expect(page.locator('.directions').first()).toBeVisible();
  await page.getByRole('button', { name: 'Review log sheets →' }).click();
  await expect(page.getByRole('heading', { name: 'Planned daily logs' })).toBeVisible();
  await assertFits(page); await capture(page, 'desktop-logs');
  await page.setViewportSize({ width: 768, height: 1024 }); await assertFits(page); await capture(page, 'tablet-logs');
  await page.setViewportSize({ width: 390, height: 844 }); await assertFits(page); await capture(page, 'mobile-logs');
  await page.locator('.mobile-log [data-log-activity^="Pre-trip inspection"] .activity-hit').click();
  await expect(page.getByRole('tooltip')).toContainText('Pre-trip inspection');
  await page.locator('.mobile-log [data-log-activity^="Pre-trip inspection"]').press('Escape');
  expect(await page.locator('.mobile-log .time-scroller').evaluate(node => node.scrollWidth <= node.clientWidth)).toBeTruthy();
  await expect(page.locator('.mobile-log .duty-graph')).toContainText('24:00');
  await page.getByRole('button', { name: 'Events', exact: true }).click(); await expect(page.locator('.log-events')).toBeVisible(); await capture(page, 'mobile-events');
  await page.getByRole('tab', { name: 'Route', exact: true }).click();
  const downloadEvent = page.waitForEvent('download'); await page.getByRole('button', { name: 'Download plan', exact: true }).click();
  const download = await downloadEvent; expect(download.suggestedFilename()).toMatch(/^farooqtrucks-plan-.*\.json$/);
  await capture(page, 'mobile-route');
  await page.getByRole('tab', { name: 'Plan trip', exact: true }).click(); await capture(page, 'mobile-plan');
  await page.setViewportSize({ width: 320, height: 700 }); await assertFits(page);
  await page.goto('/logs');
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Plan a trip to generate your log sheets' })).toBeVisible();
  await page.getByRole('tab', { name: 'Route', exact: true }).click();
  await expect(page).toHaveURL(/\/route$/);
  await expect(page.getByRole('heading', { name: 'Plan a trip to see your route and stops' })).toBeVisible();
  await page.goBack();
  await expect(page).toHaveURL(/\/logs$/);
  await expect(page.getByRole('heading', { name: 'Plan a trip to generate your log sheets' })).toBeVisible();
  await assertFits(page);
  expect(errors).toEqual([]);
});

test('field validation, provider error, help dialog and cancellation', async ({ page }) => {
  let planningRequests = 0;
  page.on('request', request => { if (request.method() === 'POST' && request.url().includes('/api/trips/plan/')) planningRequests += 1; });
  await page.goto('/');
  await page.getByRole('combobox', { name: 'Current location', exact: true }).fill('');
  await page.getByRole('button', { name: 'Plan route & logs →' }).click();
  await expect(page.getByText('Enter a city and state, or a full address.')).toBeVisible();
  await page.getByRole('combobox', { name: 'Current location', exact: true }).fill('Chicago, IL');
  const cycle = page.getByRole('spinbutton', { name: 'Current cycle used (hrs)', exact: true });
  await cycle.fill('71');
  await expect(page.getByText('Enter hours between 0 and 70.')).toBeVisible();
  await expect(cycle).toHaveAttribute('aria-invalid', 'true');
  expect(planningRequests).toBe(0);
  await page.getByRole('combobox', { name: 'Pickup location', exact: true }).fill('Springfield, IL');
  await expect(page.getByText('Enter hours between 0 and 70.')).toBeVisible();
  await page.getByRole('button', { name: 'Plan route & logs →' }).click(); await expect(page.getByText('Enter hours between 0 and 70.')).toBeVisible();
  expect(planningRequests).toBe(0);
  for (const invalid of ['-1', '']) {
    await cycle.fill(invalid);
    await expect(page.getByText('Enter hours between 0 and 70.')).toBeVisible();
  }
  for (const valid of ['0', '70', '20.5']) {
    await cycle.fill(valid);
    await expect(page.getByText('Enter hours between 0 and 70.')).toBeHidden();
    await expect(cycle).toHaveAttribute('aria-invalid', 'false');
  }
  await cycle.fill('20');
  await page.route('**/api/trips/plan/', route => route.fulfill({ status: 502, contentType: 'application/json', body: JSON.stringify({ detail: 'The map service is unavailable. Please try again shortly.' }) }));
  await page.getByRole('button', { name: 'Plan route & logs →' }).click(); await expect(page.getByRole('alert')).toContainText('The map service is unavailable');
  await page.getByRole('button', { name: 'Explain cycle hours' }).click(); await expect(page.getByRole('dialog')).toContainText('34-hour rest'); await page.getByRole('button', { name: 'Got it' }).click();
  await page.unroute('**/api/trips/plan/');
  await page.route('**/api/trips/plan/', route => new Promise(resolve => setTimeout(() => { route.abort().catch(() => {}); resolve(); }, 1000)));
  await page.getByRole('button', { name: 'Plan route & logs →' }).click(); await expect(page.getByRole('button', { name: 'Cancel', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click(); await expect(page.getByRole('button', { name: 'Plan route & logs →' })).toBeEnabled();
});

test('70 used hours: real restart, multiple log days, optional details and print all sheets', async ({ page }) => {
  await page.goto('/'); await page.getByRole('spinbutton', { name: 'Current cycle used (hrs)', exact: true }).fill('70');
  const responsePromise = page.waitForResponse(r => r.url().includes('/api/trips/plan/') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Plan route & logs →' }).click(); const response = await responsePromise;
  expect(response.status()).toBe(200); const plan = await response.json();
  expect(plan.summary.cycle_restarts).toBe(1); expect(plan.daily_logs.length).toBeGreaterThan(1);
  expect(plan.events[0].duration_seconds).toBe(34 * 3600);
  await page.getByRole('button', { name: 'Review log sheets →' }).click();
  await expect(page.locator('.day-choice')).toHaveCount(plan.daily_logs.length);
  await page.locator('.day-choice').last().click(); await expect(page.locator('.log-desktop .log-sheet')).toHaveAttribute('aria-label', `Daily log ${plan.daily_logs.at(-1).date}`);
  await page.getByRole('button', { name: 'Sheet details', exact: true }).click();
  await page.getByRole('textbox', { name: 'Driver', exact: true }).fill('Farooq'); await page.getByRole('textbox', { name: 'Carrier name', exact: true }).fill('farooqtrucks');
  await page.getByRole('button', { name: 'Save details' }).click(); await expect(page.locator('.log-desktop .sheet-details')).toContainText('Farooq');
  await expect(page.getByRole('textbox', { name: /signature/i })).toHaveCount(0);
  await page.locator('.day-choice').first().click();
  await page.locator('.log-desktop [data-log-activity^="Cycle restart"] .activity-hit').hover();
  await expect(page.getByRole('tooltip')).toContainText('Full activity:');
  await expect(page.getByRole('tooltip')).toContainText('earlier daily hours');
  await page.locator('.log-desktop [data-log-activity^="Cycle restart"]').press('Escape');
  await page.locator('.day-choice').last().click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByText(/driver.s signature/i)).toHaveCount(0);
  await page.getByRole('tab', { name: 'Route', exact: true }).click();
  const savedDownload = page.waitForEvent('download'); await page.getByRole('button', { name: 'Download plan', exact: true }).click();
  const saved = await savedDownload; const savedPlan = JSON.parse(await readFile(await saved.path(), 'utf-8'));
  expect(savedPlan).not.toHaveProperty('sheet_signatures');
  expect(savedPlan.sheet_details).toEqual({ driver: 'Farooq', carrier: 'farooqtrucks' });
  await page.getByRole('tab', { name: 'Daily logs', exact: true }).click();
  await page.evaluate(() => { window.print = () => { window.__printCalled = true; window.dispatchEvent(new Event('afterprint')); }; });
  await page.getByRole('button', { name: 'Print logs', exact: true }).click(); await expect.poll(() => page.evaluate(() => window.__printCalled)).toBeTruthy();
  await expect(page.locator('.print-only .log-sheet')).toHaveCount(plan.daily_logs.length);
  await expect(page.locator('.print-only')).not.toContainText(/signature|unsigned/i);
  await expect(page.locator('.print-only .log-sheet').last().locator('.sheet-details')).toContainText('Farooq');
  await page.emulateMedia({ media: 'print' }); await capture(page, 'print-multiple-days');
  await expect(page.locator('.skip-link')).toBeHidden();
  const pdf = await page.pdf({ path: `${captureDir}/planned-logs.pdf`, preferCSSPageSize: true, printBackground: true });
  expect((pdf.toString('latin1').match(/\/Type\s*\/Page\b/g) || []).length).toBe(plan.daily_logs.length);
});
